---
title: "Untitled"
author: "Zixuan Guan"
date: "11/18/2017"
output: html_document
---
## Graph1 ##

```{r}
# table 11(new processed table uploaded)
# Change of hours between year 2006 and year 2016 for 12 activities 

setwd("~/Downloads/GR5293_data_visualization_final_project-master/data")

t11<-read.csv("t11_processed.csv",header = T,as.is = T)
t11_sub<-t11[t11$X.1== '',]
t11_sub<-t11_sub[-1,-1]
t11_sub$y2006 = apply(t11_sub[,c(3,4,5,6)],1,mean)
t11_sub$y2016 = apply(t11_sub[,c(43,44,45,46)],1,mean)
t11_diff<-t11_sub[,c(1,47,48)]
t11_diff$diff<-t11_diff$y2016-t11_diff$y2006
par( mar=c(6,10,5,5)) 
cols<-c("red","green")[(t11_diff$diff>0)+1]
colnamesbarplot <- t11_diff$X

barplot(t11_diff$diff,main = "Change of hours between year 2006 and year 2016 for 12 activities ",names.arg = colnamesbarplot, las=1, border = NA,space = 1, horiz = T, axes = F,col = cols,cex.names=0.5)
abline(v=c(-0.1,0,0.1),col="Grey")
axis(1, at=seq(-0.1,0.1, by=0.1),labels=c("-0.1","0","0.1"),lwd=0, lwd.ticks=1)

```

## Graph 2 ##

```{r}
# table 2 (new processed table uploaded)
# sub_group by weekdays vs weekengd & holidays
# dodge

setwd("~/Downloads/GR5293_data_visualization_final_project-master/data")

library(reshape2)

t2<-read.csv("t2_processed.csv",header = T,as.is = T)
t2_sub<-t2[t2$Activity_sub== '',]
t2_sub$person_weekends[t2_sub$person_weekends== "~0"]<-"0"
t2_sub$person_weekends<-as.numeric(t2_sub$person_weekends)
t2_sub<-t2_sub[,c(1,7,8)]
colnames(t2_sub)<-c("Activity","Weekdays","Weekends & Holidays")
t2_sub.m<-melt(t2_sub)
p1<-ggplot(t2_sub.m, aes(Activity, value, fill = variable)) + 
      geom_bar(stat="identity", position = "dodge") +
      labs(title="Different activites average percentage separate by weekdays or not",x ="Activities", y = "Average percentage")+
      scale_x_discrete(expand = c(0,0),
                      breaks=t2_sub$Activity[1:18],
                      labels=t2_sub$Activity[1:18]) + 
      scale_y_continuous(expand = c(0,0))+
      coord_flip() 

## adjust filling color an legend

newpalette<-colorRampPalette(c("#014d64","#6794a7"))(2)
p1 + scale_fill_manual(values=newpalette,
                      name = "Legend") +
   theme_bw() + 
  theme(panel.grid=element_blank(),panel.border=element_blank(),axis.line=element_line(size=1,colour="black"))
```
```{r}
# stack

p1<-ggplot(t2_sub.m, aes(Activity, value, fill = variable)) + 
      geom_bar(stat="identity") +
      labs(title="Different activites average percentage separate by weekdays or not",x ="Activities", y = "Average percentage")+
      scale_x_discrete(expand = c(0,0),
                      breaks=t2_sub$Activity[1:18],
                      labels=t2_sub$Activity[1:18]) + 
      scale_y_continuous(expand = c(0,0))+
      coord_flip() 

## adjust filling color an legend

newpalette<-colorRampPalette(c("#014d64","#6794a7"))(2)
p1 + scale_fill_manual(values=newpalette,
                      name = "Legend") +
   theme_bw() + 
  theme(panel.grid=element_blank(),panel.border=element_blank(),axis.line=element_line(size=1,colour="black"))
```

## Graph 3##

```{r}
# Personal care activities subgroup by sex

library(reshape2)
setwd("~/Downloads/GR5293_data_visualization_final_project-master/data")

t1<- read.csv("t1_processed.csv",header=T,as.is=T)
t1_personal<- t1[t1$Activity== 'Personal care activities',]
t1_personal_sub<-t1_personal[,c(2,7,8)]
t1_personal_sub$Activity_sub[1]<-"Personal care activities total"
t1_personal_sub.m <-melt(t1_personal_sub,id="Activity_sub")
t1_personal_sub.m$value<-as.numeric(t1_personal_sub.m$value)

p1<-ggplot(t1_personal_sub.m, aes(Activity_sub, value, fill = variable)) + 
      geom_bar(stat="identity", position = "dodge") +
      labs(title="Different Personal care activities average hours separate by sex",x ="Activities", y = "Average hours")+
      scale_x_discrete(expand = c(0,0),
                      breaks=t1_personal_sub$Activity_sub[1:6],
                      labels=t1_personal_sub$Activity_sub[1:6]) + 
      scale_y_continuous(expand = c(0,0))+
      coord_flip() 

## adjust filling color an legend

newpalette<-colorRampPalette(c("#014d64","#6794a7"))(2)
p1 + scale_fill_manual(values=newpalette,
                      name = "Sex") +
   theme_bw() + 
  theme(panel.grid=element_blank(),panel.border=element_blank(),axis.line=element_line(size=1,colour="black"))
```

```{r}
# Household care activities subgroup by sex

t1_household <- t1[t1$Activity== 'Household activities',]
t1_household_sub<-t1_household[,c(2,7,8)]
t1_household_sub$Activity_sub[1]<-"Household activities total"
t1_household_sub.m <-melt(t1_household_sub,id="Activity_sub")
t1_household_sub.m$value<-as.numeric(t1_household_sub.m$value)

p1<-ggplot(t1_household_sub.m, aes(Activity_sub, value, fill = variable)) + 
      geom_bar(stat="identity", position = "dodge") +
      labs(title="Different Household activities average hours separate by sex",x ="Activities", y = "Average hours")+
      scale_x_discrete(expand = c(0,0),
                      breaks=t1_household_sub$Activity_sub[1:11],
                      labels=t1_household_sub$Activity_sub[1:11]) + 
      scale_y_continuous(expand = c(0,0))+
      coord_flip() 

## adjust filling color an legend

newpalette<-colorRampPalette(c("#014d64","#6794a7"))(2)
p1 + scale_fill_manual(values=newpalette,
                      name = "Sex") +
   theme_bw() + 
  theme(panel.grid=element_blank(),panel.border=element_blank(),axis.line=element_line(size=1,colour="black"))
```

## Graph 5 ##

```{r}
# facet grouped by sex and job types

library(reshape2)
setwd("~/Downloads/GR5293_data_visualization_final_project-master/data")
t6_1 <- read.csv("t6_processed_1.csv",header=T,as.is=T)
t6_1<-t6_1[1:25,]
t6_1<-t6_1[nchar(t6_1$Activity_sub)==0,]
t6_1<-t6_1[,c(1,3,5,6,7)]
colnames(t6_1)<-c("Activity","Mother full time job","Mother no job",
                  "Father full time job", "Father no job")
t6_1.m<-melt(t6_1)
t6_1.m$value<-as.numeric(t6_1.m$value)
t6_1.m$sex<-c(rep("Female", times = 18),rep("Male", times = 18))
t6_1.m$variable<-c(rep("Full time", times = 9),rep("No employed", times = 9),rep("Full time", times = 9),rep("No employed", times = 9))
p1<-ggplot(t6_1.m, aes(Activity, value, fill = variable)) + 
      geom_bar(stat="identity", position = "dodge") +
      labs(title="Different activities average hours separate by sex and jobs",x ="Activities", y = "Average hours")+
      scale_x_discrete(expand = c(0,0),
                      breaks=t6_1$Activity[1:9],
                      labels=t6_1$Activity[1:9]) + 
      scale_y_continuous(expand = c(0,0))+
      facet_wrap(~sex)+
      coord_flip() 

newpalette<-colorRampPalette(c("#014d64","#6794a7"))(2)
p1 + scale_fill_manual(values=newpalette,
                      name = "Job type") +
   theme_bw() + 
  theme(panel.grid=element_blank(),panel.border=element_blank(),axis.line=element_line(size=1,colour="black"))

```


