---
title: "groupby_job_sex"
author: "Yitong Hu  (yh2875)"
date: "2017/11/16"
output: html_document
---

```{r}
library(ggplot2)
library(reshape2)
library(fastR)
library(RColorBrewer)
library(grid)
library(extracat)
```

```{r}
# read and clean table 6
t6_1 <- read.csv("../data/t6_processed_1.csv",header=T,as.is=T)
t6_1<-t6_1[1:25,]
t6_1<-t6_1[nchar(t6_1$Activity_sub)==0,]
t6_1<-t6_1[,c(1,3,5,6,7)]
colnames(t6_1)<-c("Activity","Mother with full time job","Mother no job",
                  "Father with full time job", "Father no job")
t6_1.m<-melt(t6_1)
t6_1.m$sex = substr(t6_1.m$variable,1,6)
t6_1.m$job = substr(t6_1.m$variable,8,100)
t6_2<-t6_1.m[,c(3,4,5)]
```

```{r}
library(datasets)
library(ggplot2)
df <- data.frame(Titanic)
ggplot(df, aes(x = Class, y = Freq, fill = Survived))
geom_bar(stat = "identity", position = "dodge") + facet_wrap(~Sex)
```


```{r}
ggplot(df, aes(x = Class, y = Freq, fill = Survived))
geom_bar(stat = "identity", position = "dodge") + facet_wrap(~Sex)

t6_2

ggplot(t6_1.m, aes(factor(Activity), value, fill = variable)) + 
  geom_bar(stat="identity", position = "dodge") + facet_wrap(~Sex) 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  labs(title="Different activites average hours separate by job types and sex in a family",
        x ="Activities", y = "Annual hours")
```


```{r fig.width = 8, fig.height = 5}
counts = as.data.frame(table(airlineArrival))
colors<-c(brewer.pal(11, "RdYlGn")[2], brewer.pal(11, "RdYlGn")[11])

vcd::mosaic(sex ~ job, t6_2,
            gp = gpar(fill = colors),
            direction = c("v", "v", "h"),
            labeling_args=list(rot_labels=c(bottom=20,top=0),gp_labels=(gpar(fontsize=10))))
```